---
- hosts: all

  vars:
    ip: '{{ ip_addr }}'
    
  tasks:
    - debug:
        msg: "Running PLAYBOOK TEST"
    
    - name: return hostname
      command: hostnamectl
      register: hname

    - debug: 
        var: hname
        
    - debug:
        var: ip 
