---
- hosts: all

  vars:
    
  tasks:
    - debug:
        msg: "Running PLAYBOOK TEST"
    
    - name: return hostname
      command: hostnamectl
      register: hname

    - debug: 
        var: hname
        
    - debug:
        msg: {{ ip_addr }}
    
    - debug
        msg: {{ var1 }}
        
    - name: Display all variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname]
        verbosity: 4
